### ISSUE TITLE
Gnome 3.16 compatibility

### ISSUE THREAD

**Issue by Libco** [pixel-saver/pixel-saver#21]
Not working in gnome 3.16, just editing metadata is not enough.

**Comment by deadalnix** [comment]
Could you make a PR then ?

**Comment by geecko86** [comment]
Not sure what PR means in this case. Gnome won't launch the extension.

> TypeError: Meta.prefs_get_theme is not a function

**Comment by deadalnix** [comment]
PR is shorthand for pull request. But I misread @Libco 's report (read just editing metadata is enough, skipping the not).

I'm on debian and 3.16 is not there yet. It sound like there was an API change in Meta, I can look into it and ultimately try to come up with a fix, but I won't be able to test the fix.

**Comment by geecko86** [comment]
I'd be glad to test it :)

**Comment by deadalnix** [comment]
OK I'll try to find some time this week end to look into this. Please pig me here if I forget about this.

**Comment by astralaster** [comment]
Nice to see you are already working on 3.16 compatibility. I just came up with your extension and its a musthave for gnome.

**Comment by mschubert** [comment]
+1, I'm happy to test as well.

**Comment by lsde** [comment]
@deadalnix hi, have you found about that API change?

**Comment by silentboatman** [comment]
Maybe it's related to this post from the commits-list mailing list: 
[[metacity] theme: don't use meta_prefs_get_theme to detect theme type](https://mail.gnome.org/archives/commits-list/2015-April/msg00812.html)

I haven't had the time to test it though..

**Comment by deadalnix** [comment]
I'm so fed up with these random API changes...

@silentboatman yes it look like it is the change that broke everything. Thank for finding it.

**Comment by deadalnix** [comment]
Change commit: https://git.gnome.org/browse/mutter//commit/?id=5e9db422c95e278f280501af2c343dbec16177b6

You'd think they would document the new shit before removing the old one, but nope.....
https://developer.gnome.org/search?q=MetaTheme

Brilliant !

**Comment by deadalnix** [comment]
I asked in the gnome-shell ML, let's see what the tell me.

**Comment by silentboatman** [comment]
When I changed to *Gtk.Settings.get_default().gtk_theme_name* as suggested on the gnome-shell ML, the error disappeared. But I got a new one.. Here's the output:
> Gjs-Message: JS WARNING: [/usr/share/gnome-shell/extensions/pixel-saver@deadalnix.me/decoration.js 215]: anonymous function does not always return a value
> Gjs-Message: JS WARNING: [/usr/share/gnome-shell/extensions/pixel-saver@deadalnix.me/buttons.js 112]: anonymous function does not always return a value
> Gjs-Message: JS LOG: [pixel-saver]: 'appmenu' is not a valid button.
> Gjs-Message: JS LOG: Extension "pixel-saver@deadalnix.me" had error: Error: Expected type interface for Argument 'file' but got type 'string'

Couldn't figure it out though..

The git diff I made is [here](https://gist.github.com/silentboatman/ee23d5752ce16397e6ee). I'm running Gnome Shell 3.16.1 on Arch.

**Comment by deadalnix** [comment]
Thank you so much. As you guys may have seen I've been away the past 2 weeks, and will not be very available before next week. Digging into this when I'm back.

**Comment by essen** [comment]
Interested in this plugin but unfortunately running 3.16. Wondering if you made any progress? :-)

**Comment by deadalnix** [comment]
@silentboatman do you have a file/line for this ?
Gjs-Message: JS LOG: Extension "pixel-saver@deadalnix.me" had error: Error: Expected type interface for Argument 'file' but got type 'string'

**Comment by deadalnix** [comment]
@silentboatman I think it may be the css load in button.js

Can you try to comment this line:
St.ThemeContext.get_for_stage(global.stage).get_theme().load_stylesheet(cssPath);

**Comment by silentboatman** [comment]
I couldn't find what line that error came from.. But when I commented the `St.ThemeContext.get_for_stage()`-line I got some success!

On boot the `"Expected type interface.."`-error doesn't show up and and the extension work. Hurray!

But when I inactivat it (with the tweek tool) the same error message show up.. Strange.

Another error message that I get everytime I select a window (and that may och may not be related) is this:

> Gjs-WARNING **: JS ERROR: TypeError: appMenu._label.setText is not a function
> updateAppMenu@/usr/share/gnome-shell/extensions/pixel-saver@deadalnix.me/app_menu.js:41

**Comment by deadalnix** [comment]
Awesome. It seems that this method expect a GFile and not a string in 3.16 . Javascript is so awesome. Thing is, I have no idea how to create a GFile.

**Comment by silentboatman** [comment]
Success! I found info about GFile [here](http://www.roojs.com/seed/gir-1.2-gtk-3.0/gjs/Gio.File.html#Gio-method-file_new_for_path) and it seem to work for me. Here's the [patch](https://gist.github.com/silentboatman/c8eeae2c6b4ad3f69db8).

But I still get that `_label.setText is not a function` error..

**Comment by macramole** [comment]
+1 to this

**Comment by deadalnix** [comment]
Fuck it, this patch break compatibility with gnome < 3.16 . :fire:

**Comment by deadalnix** [comment]
@silentboatman I integrated your patches, and created a tag 1.5, which will be the last version to support 3.14.

**Comment by essen** [comment]
Hm current master doesn't seem to work for me, even after doing "alt+f2 r". Am I supposed to do something else? How do I debug this?

**Comment by deadalnix** [comment]
alt+F2, type lg

Click on extension. Look at pixel saver. Report the error you find in there.

**Comment by essen** [comment]
No errors. Let me restart and see.

**Comment by essen** [comment]
OK after reboot I got an error about missing xprop (sorry about that, I thought I installed it but guess I removed it after) and then after another reboot it worked. Thanks a bunch!

**Comment by mschubert** [comment]
Works fine here on Arch/3.16. :+1:

**Comment by herrlado** [comment]
works fine with gnome 3.16/gentoo

**Comment by Hanzei** [comment]
Can we close this one?
